apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
    securityContext:
      runAsNonRoot: true
      runAsUser: 11000
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: notDefault
status: {}